const BUILD_DATE = new Date().toISOString().split("T")[0];

export default function Footer() {
  return (
    <footer className="mt-10">
      <div className="container-main">
        <div className="footer-separator" />
        <div>
          &copy; {new Date().getFullYear()} Fanyou Wu
        </div>
        <div className="text-gray-500 text-xs mt-1">
          Generated by{" "}
          <a href="https://code.claude.com/docs/en/overview" target="_blank" rel="noopener noreferrer">
            Claude Code
          </a>
          . Updated on <span className="font-mono">{BUILD_DATE}</span>.
        </div>
      </div>
    </footer>
  );
}
