const BUILD_DATE = new Date().toISOString().split("T")[0];

export default function Footer() {
  return (
    <footer className="mt-10">
      <div className="container-main">
        &copy; Copyright {new Date().getFullYear()} Fanyou Wu. Generated by{" "}
        <a href="https://code.claude.com/docs/en/overview" target="_blank" rel="noopener noreferrer">
          Claude Code
        </a>
        . Updated on {BUILD_DATE}.
      </div>
    </footer>
  );
}
